### ISSUE TITLE
Missing something inside "get started" section within the Readme file?

### ISSUE THREAD

**Issue by rzecchini** [awt2542/ViewController-for-Framer#1]
Seems that to initialize the module you have to operate quite differently.
From your Readme: (doesnt work)

```
Views = require "ViewController"
Views.initialView = sketch.homepage
```

With constructor (doesnt work, ??)

```
ViewController = require "ViewController" 
Views = new ViewController
Views.initialView = sketch.homepage
```

With constructor (it works!)

```
ViewController = require "ViewController" 
Views = new ViewController
    initialView: sketch.homepage
```

Am I missing something?

**Comment by awt2542** [comment]
That's probably right. I'll update the readme and have a look

**Comment by awt2542** [comment]
Readme has been updated. It was all wrong - thanks for letting me know! You need to set initialView with the constructor :)
