### ISSUE TITLE
Numbers in Layer names

### ISSUE THREAD

**Issue by damianogui** [awt2542/ViewController-for-Framer#13]
Seems like putting any number inside a Layer name results in the error:
`TypeError: undefined is not an object (evaluating 'newView.parent = _this')`
It's a big issue if for example one is working with a big prototype and needs to have numbered screens. Is there a workaround?

**Comment by awt2542** [comment]
This is a tricky one. The plugin ignores numbers since Framer often adds these automatically when two layers share the same name. This leads to unexpected results when you have multiple layers named "slideIn_homescreen". I can probably rewrite the regex so it only ignores numbers at the end.

**Comment by awt2542** [comment]
Hi! There's now a way to restore the original names after import. I wrote a small module to make this easier: https://github.com/awt2542/restoreImportedNames-for-Framer

**Comment by damianogui** [comment]
Thanks!
