### ISSUE TITLE
Usage without Sketch

### ISSUE THREAD

**Issue by ortonomy** [awt2542/ViewController-for-Framer#16]
I'm trying to use this module without Sketch, but it doesn't work

```
# set up view controller
Views = new ViewController
    initialView: initialView

# set up views
initialView = new Layer
    width: Screen.width
    height: Screen.height

storyView = new Layer
    width: Screen.width
    height: Screen.height
```

The prototype shows `storyView` above the initialView = i.e. module is not putting initialView as the top layer, or hiding the other layer.

**Comment by awt2542** [comment]
This is because initialView doesn't exist when you try to set it. Move the initialView definition above the ViewController and it should work
