### ISSUE TITLE
Adding custom animation for magicMove

### ISSUE THREAD

**Issue by tehfailsafe** [awt2542/ViewController-for-Framer#2]
Would it be possible add a custom animation on magicMove transitions for single elements? 

For example, on the image gallery when the bird zooms in what if I want to add a floating action button circle on in the bottom right, but instead of opacity fading up I could set it slide up from the bottom. 

Maybe something like :

```
sketch.item1.on Events.Click, -> 
    ViewController.magicMove sketch.detail, curve: "spring(400, 35)", onComplete: () ->
           sketch.fab.animate y: Screen.height - 100

```

Or something similar? Thoughts? I am loving the magicMove transitions but some details need a bit more prescriptive animation.

**Comment by awt2542** [comment]
I've decided to move magic move to a separate branch for now since it added too much complexity to the module. I'll open this up again when/if magic move makes it back.
