### ISSUE TITLE
MagicMove: Sublayers causes duplication

### ISSUE THREAD

**Issue by chadobado** [awt2542/ViewController-for-Framer#4]
Two problems illustrated by this example (will open a second issue to track the other):
1. When adding a named layer to a parent layer, magicMove does its magic on the correctly named layer - but the parent is not matched so is faded out (which also includes its children) so we end up with the intended named layer being animated correctly but then a duplicate of it simultaneously fading out.

Example:  [Link](http://share.framerjs.com/dou85ex9mjej/)
# Relevant code:

```
    # fade out unused layers
    for remainingLayer, layer of existingLayers
        tempCopy = layer.copy()
        tempCopy.superLayer = newView
        animationObj = 
                properties:
                    opacity: 0
        _.extend animationObj, animationOptions
        fadeOut = tempCopy.animate animationObj
        tempCopy.on Events.AnimationEnd, -> @destroy()
```

**Comment by awt2542** [comment]
I've decided to move magic move to a separate branch for now since it added too much complexity to the module. I'll open this up again when/if magic move makes it back.
