### ISSUE TITLE
MagicMove: Does not take into consideration location of parent layers

### ISSUE THREAD

**Issue by chadobado** [awt2542/ViewController-for-Framer#5]
Second problem illustrated by this example:
1. When animating nested children, magicMove uses the x/y of the Layer relevant to it's parent and not the actual position on the screen.  I experimented with using layer.screenFrame.x/y with some success.

Example:  [Link](http://share.framerjs.com/dou85ex9mjej/)

**Comment by awt2542** [comment]
I've decided to move magic move to a separate branch for now since it added too much complexity to the module. I'll open this up again when/if magic move makes it back.
